spring:
  application:
    name: UberSockerService
  datasource:
    url: jdbc:mariadb://localhost:3306/Uber_Db_Local
    username: luffy
    password: ${db_password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
